version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine3.16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.db
volumes:
  postgres_data: